### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by Martype** [tsdotnet/linq#1]
Hi, imho the documentation is missing some essential information. You start with something like 
`const source = range(1,100);`
but how to start with something like an indexed type? How to transform objects into an Iterable<T>?

`let _records: { [id: string]: DataSetInterfaces.EntityRecord; } = getRecords();`
`let _recordsAsIterable: Iterable<DataSetInterfaces.EntityRecord>;`
`#...pls tell me the code to insert here...`
`let lnq = linq(_recordsAsIterable);`

**Comment by electricessence** [comment]
Hello, sorry for the late reply.

I might misunderstand the question.  Are you asking how to get your `_records` to be iterable?

A possibility would be this:
```ts
_recordsAsIterable =
    linq(Object.keys(_records))
    .transform(k => {id:k, enity:_records[k]});
```

And after that, your last line with `lnq` is redundant because it's already a linq iterable.

Does that help?  Or do you only need the value and not the `id`?

**Comment by Martype** [comment]
Hi, thanks for your help, but apparently there is something wrong with the code you've posted. What is "k"? You probably meant "key" there, but this doesn't work neither.

![image](https://user-images.githubusercontent.com/1420317/99377299-559e3780-28c6-11eb-8663-29bf4cd4f29d.png)
![image](https://user-images.githubusercontent.com/1420317/99377642-bcbbec00-28c6-11eb-99e3-375172748927.png)

**Comment by electricessence** [comment]
I corrected the code, yes... `k` meant `key`.

**Comment by electricessence** [comment]
I'm looking at this further.   There are plenty of tests that prove the code works.  I think your implementation is off.
Hence why we use TypeScript. :)

**Comment by electricessence** [comment]
BTW, is it "enity" or "entity"? :P

**Comment by electricessence** [comment]
So let's take this one step at a time as it's been months.

https://github.com/tsdotnet/linq/blob/master/src/linq.ts#L60-L68
`.transform()` is just a shortcut for passing an _iterable transform function_ which isn't a `k=>result` function.

https://github.com/tsdotnet/linq/blob/master/src/linqExtended.ts#L117-L125
Try using `LinqExtended` instead and then replace `.transform` with `.select`.

**Comment by electricessence** [comment]
Or if you don't want to use `LinqExtended` then you need to use the `select` iterable transform function.
Like so:
```ts
_recordsAsIterable =
    linq(Object.keys(_records))
    .transform(select(k => {id:k, enity:_records[k]}));
```

Sorry for the confusion.  Hope that helps.
It's like this because TS/JS don't have extensions like C# so you have to think a bit different.

**Comment by electricessence** [comment]
For more context, you can use any iterable transform function: (like `groupBy`, etc)
https://github.com/tsdotnet/linq/tree/master/src/transforms

So think of a transform function like the extensions provided by LINQ.  It would be like referring to the static version of `.Select`.

**Comment by electricessence** [comment]
I'm gonna close this for now, but you're welcome to continue commenting and questioning.
